<?php require_once('Connections/indust2.php'); ?>
<?php
if (!function_exists("GetSQLValueString")) {
function GetSQLValueString($theValue, $theType, $theDefinedValue = "", $theNotDefinedValue = "") 
{
  $theValue = get_magic_quotes_gpc() ? stripslashes($theValue) : $theValue;

  $theValue = function_exists("mysql_real_escape_string") ? mysql_real_escape_string($theValue) : mysql_escape_string($theValue);

  switch ($theType) {
    case "text":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;    
    case "long":
    case "int":
      $theValue = ($theValue != "") ? intval($theValue) : "NULL";
      break;
    case "double":
      $theValue = ($theValue != "") ? "'" . doubleval($theValue) . "'" : "NULL";
      break;
    case "date":
      $theValue = ($theValue != "") ? "'" . $theValue . "'" : "NULL";
      break;
    case "defined":
      $theValue = ($theValue != "") ? $theDefinedValue : $theNotDefinedValue;
      break;
  }
  return $theValue;
}
}

$editFormAction = $_SERVER['PHP_SELF'];
if (isset($_SERVER['QUERY_STRING'])) {
  $editFormAction .= "?" . htmlentities($_SERVER['QUERY_STRING']);
}

if ((isset($_POST["MM_insert"])) && ($_POST["MM_insert"] == "form1")) {
  $insertSQL = sprintf("INSERT INTO bands (name, id) VALUES (%s, %s)",
                       GetSQLValueString($_POST['name'], "text"),
                       GetSQLValueString($_POST['id'], "text"));

  mysql_select_db($database_indust2, $indust2);
  $Result1 = mysql_query($insertSQL, $indust2) or die(mysql_error());

  $insertGoTo = "bandsTest.php";
  if (isset($_SERVER['QUERY_STRING'])) {
    $insertGoTo .= (strpos($insertGoTo, '?')) ? "&" : "?";
    $insertGoTo .= $_SERVER['QUERY_STRING'];
  }
  header(sprintf("Location: %s", $insertGoTo));
}

mysql_select_db($database_indust2, $indust2);
$query_Recordset1 = "SELECT name FROM bands";
$Recordset1 = mysql_query($query_Recordset1, $indust2) or die(mysql_error());
$row_Recordset1 = mysql_fetch_assoc($Recordset1);
$totalRows_Recordset1 = mysql_num_rows($Recordset1);
?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>Untitled Document</title>
</head>
<?php 




$bands = array(
"Devo"
,"51 Peg"
,"Acumen Nation"
,"Allerseelen"
,"And One"
,"Android Lust"
,"Angelspit"
,"Apoptygma Berzerk"
,"Arditi"
,"Armageddon Dildos"
,"A Split Second"
,"Assemblage 23"
,"Aural Vampire"
,"The Axis of Perdition"
,"Bile"
,"Black Light Burns"
,"Blam Honey"
,"Blood Axis"
,"Blue Stahli"
,"Braindead Soundmachine"
,"Cabaret Voltaire"
,"Celldweller"
,"Chemlab"
,"Chris & Cosey"
,"Chrome"
,"The Clay People"
,"Clock DVA"
,"Coil"
,"Collide"
,"Combichrist"
,"Controlled Bleeding"
,"Crocodile Shop"
,"Crossbreed"
,"Cyanotic"
,"Das Ich"
,"Dawn of Ashes"
,"DB9D9"
,"Deadly Apples"
,"Delerium"
,"D espairsRay"
,"Deutsch-Amerikanische Freundschaft"
,"Diatribe"
,"Die Form"
,"Die Krupps"
,"Die Warzau"
,"Doubting Thomas"
,"dreDDup"
,"Download"
,"D.M.Y"
,"Ehron VonAllen"
,"Einst√ºrzende Neubauten"
,"Emigrate"
,"Eve of Destiny"
,"Fad Gadget"
,"Fear and the Nervous System"
,"Feindflug"
,"Filter"
,"Flesh Field"
,"Foetus"
,"Forgotten Sunrise"
,"Freak XXI"
,"Front 242"
,"Front Line Assembly"
,"Funeral for a Clown"
,"Funker Vogt"
,"Genitorturers"
,"God Lives Underwater"
,"God Module"
,"Godhead"
,"GPKism"
,"Grauzone"
,"Gravity Euphonic"
,"Gravity Kills"
,"Greater Than One"
,"Grendel"
,"Guniw Tools"
,"Head of David"
,"Hell on Earth"
,"Hieronymus Bosch"
,"Hocico"
,"In the Nursery"
,"Informatik"
,"Innerpartysystem"
,"Insurge"
,"Intermix"
,"Jakalope"
,"Jerk"
,"Kidneythieves"
,"Killing Joke"
,"Klinik"
,"KMFDM"
,"Koil"
,"Kreuzweg Ost"
,"Laibach"
,"Leaether Strip"
,"Left Spine Down"
,"Les Joyaux De La Princesse"
,"Le√¶ther Strip"
,"Lights of Euphoria"
,"Luftwaffe"
,"Machines of Loving Grace"
,"The Mad Capsule Markets"
,"Makine"
,"Manufacture"
,"Marilyn Manson"
,"MC 900 Foot Jesus"
,"MDFMK"
,"Meat Beat Manifesto"
,"Mindless Self Indulgence"
,"Ministry"
,"Mortiis"
,"My Life With The Thrill Kill Kult"
,"NeedleHole"
,"The Neon Judgement"
,"Neon Synthesis"
,"N17"
,"Nine Inch Nails"
,"Nitzer Ebb"
,"The Newlydeads"
,"No-Big-Silence"
,"Noisuf-X"
,"Oomph!"
,"ohGr"
,"Orgy"
,"Pailhead"
,"Pain"
,"Pankow"
,"PeaceINSERT INTO bands VALUES( Love and Pitbulls"
,"PIG"
,"Pigface"
,"Pitchshifter"
,"Psyclon Nine"
,"Puscifer"
,"Rabbit Junk"
,"Razed in Black"
,"The Retrosic"
,"Revolting Cocks"
,"Boyd Rice"
,"Rorschach Test"
,"Rotersand"
,"Rx"
,"SAM"
,"SCH"
,"Shihad"
,"Sister Machine Gun"
,"Skillet"
,"Skinny Puppy"
,"Tim Skold"
,"Snake River Conspiracy"
,"Snog"
,"Spahn Ranch"
,"SPK"
,"Stabbing Westward"
,"Stiff Valentine"
,"Suicide"
,"Suicide Commando"
,"Swamp Terrorists"
,"Swans"
,"Synchro Nine Factor"
,"Tactical Sekt"
,"Tanzwut"
,"Test Dept"
,"Throbbing Gristle"
,"Tweaker"
,"Undercover Slut"
,"Vampire State Building"
,"VAST"
,"Velvet Acid Christ"
,"Videodrone"
,"VNV Nation"
,"Vomito Negro"
,"Westwind"
,"Wolfsheim"
,"Wumpscut"
,"X-Fusion"
,"X Marks the Pedwalk"
,"YelworC"
,"The Young Gods"
,"Z EV"
,"Zeromancer"
,"Zilch"
,"Alboth!"
,"Arsenal"
,"Auschwitz 46"
,"Big Black"
,"Big Catholic Guilt"
,"Bile"
,"Bizarra Locomotiva"
,"Blood Feud"
,"Bloodstar"
,"Body Clock"
,"Bomb Everything"
,"Caspar Brotzmann"
,"Butthole Surfers"
,"Cable Regime"
,"Candiru"
,"Chemical Plant"
,"Christbait"
,"Christian Lunch"
,"Circle of Dust"
,"Cop Shoot Cop"
,"Course of Empire"
,"Helios Creed"
,"Dead World"
,"Deathless"
,"Diatribe"
,"Dogpile"
,"Drill"
,"Dystopia One"
,"Epilepsy"
,"Evil Mothers"
,"Fall Of Because"
,"Fat Hacker"
,"Fear Factory"
,"Fetish 69"
,"Flesh Volcano"
,"Foetus"
,"Foreskin 500"
,"Fuckhead"
,"Fudge Tunnel"
,"Garbage Collector"
,"Geins t Nait"
,"God"
,"Godflesh"
,"Gore"
,"Grill"
,"Grotus"
,"Gwar"
,"Headbutt"
,"Head of David"
,"Hyperhead"
,"Ice"
,"Killing Joke"
,"Kong"
,"La Muerte"
,"Lard"
,"Loggerhead"
,"Machine Head"
,"Malformed Earthborn"
,"Malhavoc"
,"Marilyn Manson"
,"Meathook Seed"
,"Melvins"
,"Milk Cult"
,"Ministry"
,"Murder Inc."
,"Nailbomb"
,"Napalm Death"
,"Nerve"
,"Neurosis"
,"Of Cabbages And Kings"
,"OLD"
,"Optimum Wound Profile"
,"Painkiller"
,"Pain Teens"
,"Laurent Pernice"
,"Phew"
,"Pigface"
,"Pitch Shifter"
,"Pore"
,"Prong"
,"Puncture"
,"Rorschach Test"
,"Savage Aural Hotbed"
,"Scorn"
,"Setrakian"
,"Sharkbait"
,"Siglo XX"
,"Sigmund und Sein Freund"
,"16-17"
,"Skatenigs"
,"Skin Chamber"
,"Skrew"
,"Skullflower"
,"Slab"
,"Slice of God"
,"Slow Burn"
,"Sonic Violence"
,"Spartak"
,"Spit"
,"Splintered"
,"Stabbing Westward"
,"Steroid Maximus"
,"Strapping Young Lad"
,"Sturm Group"
,"Suicide"
,"Sweet Tooth"
,"Terminal Cheesecake"
,"Testify"
,"Think Tree"
,"Thought Industry"
,"Three Angry Poles"
,"Transmisia"
,"Treponem Pal"
,"Trust Obey"
,"Type O Negative"
,"Luc Van Acker"
,"Wiseblood"
,"Workforce"
,"World Domination Enterprises"
,"Wreck"
,"Young Gods"
,"Zeni Geva"
,"John Zorn"
,"AAAK"
,"Abscess"
,"Absent Minded"
,"Absolute Body Control"
,"Abstinence"
,"Absurd Minds"
,"Accessory"
,"Acid Horse"
,"Active Media Disease"
,"Acumen"
,"Aghast View"
,"√†;GRUMH..."
,"A Head"
,"Aiboforcen"
,"Aircrash Bureau"
,"Ajax"
,"Alien Faktor"
,"Alien Sylvas Womb"
,"Allied Vision"
,"AmGod"
,"And Christ Wept"
,"And One"
,"Android Lust"
,"Andromeda Complex"
,"Angels & Agony"
,"Angels On Acid"
,"Angry White Mob"
,"The Anti Group"
,"A-Politiq"
,"Apoptygma Berzerk"
,"Apparatus"
,"Argyle Park"
,"Armageddon Dildos"
,"Art Academy"
,"Artefakto"
,"Arzt+Pfusch"
,"A Split Second"
,"Assemblage 23"
,"Asylum Choir"
,"ATD Convention"
,"Attrition"
,"Audio Paradox"
,"Axiome"
,"Axonal Warfare"
,"Babyland"
,"Battery Cage"
,"Battery"
,"Batz Without Flesh"
,"Benestrophe"
,"Bigod 20"
,"Biohazard PCB"
,"Bionic"
,"Biopsy"
,"Bio-Tek"
,"Birmingham 6"
,"Blackouts"
,"Black Rain"
,"Black State Choir"
,"Blast Conservatory"
,"Bleeding Stone"
,"Blind Vision"
,"Blok 57"
,"Blow"
,"Blue Eyed Christ"
,"Blutengel"
,"Bol"
,"Boom Operators"
,"Borghesia"
,"Box Car"
,"Brain Leisure"
,"Brigade Werther"
,"B-Ton-K"
,"Cabaret Voltaire"
,"Call"
,"Calva y Nada"
,"Cassandra Complex"
,"Cat Rapes Dog"
,"Cenobita"
,"Cesium 137"
,"Checkists"
,"Chemical Brothers"
,"Chem Lab"
,"Chew s Eye Shop"
,"Childman"
,"Chris and Cosey"
,"Christ Analogue"
,"Circus of Pain"
,"Claire Voyant"
,"Clay People"
,"Cleen"
,"Click Click"
,"Clock DVA"
,"Cobalt 60"
,"Code Industry"
,"Cold"
,"Collapsed System"
,"Collide"
,"Colourbox"
,"Company of State"
,"Compound"
,"Concrete Nature"
,"Consequence"
,"Consolidated"
,"Construggle Test"
,"Contagion"
,"Contingence"
,"Controlled Fusion"
,"Coptic Rain"
,"Covenant"
,"Crash A/D"
,"Crisis"
,"Crocodile Shop"
,"Crunch-O-Matic"
,"C-Tec"
,"Cubanate"
,"Cultivated Bimbo"
,"Culture Kult√ºr"
,"Cut Rate Box"
,"Cyberaktif"
,"Cyber Axis"
,"Cyber-Tec"
,"Cyborg Attack"
,"Cycloon"
,"Cymotec"
,"DAF"
,"Dance Or Die"
,"Dance 2 Trance"
,"Danse Macabre"
,"Dark Illumination"
,"Data Bank A"
,"Death & Horror Inc."
,"Death Line International"
,"Decoded Feedback"
,"Delay"
,"Delta-12N"
,"Dementia Simplex"
,"Demonix"
,"Dessau"
,"Deus Ex Machina"
,"Devoid"
,"Die Form"
,"Die Krupps"
,"Die Maschine"
,"Diesel Christ"
,"Die Warzau"
,"Digital Factor"
,"Digital Poodle"
,"Din"
,"Din_Fiv"
,"Diorama"
,"Dismembered Quietly"
,"Disposable Heroes of Hiphoprisy"
,"Distain!"
,"Dive"
,"D.J. Magic Mike"
,"D.J. Spike"
,"Dogmachine"
,"Doubting Thomas"
,"Download"
,"Drag"
,"Dresden"
,"Drown"
,"DRP"
,"Drug Free America"
,"Drunkness"
,"The Dust Of Basement"
,"ECM"
,"ECO"
,"Econoline Crush"
,"E-Craft"
,"Electric Hellfire Club"
,"Electro Assassin"
,"Emergency Broadcast Network"
,"Empirion"
,"Endanger"
,"En Esch"
,"En Halvkokt I Folie"
,"Equinox"
,"Ethyl Meatplow"
,"Evils Toy"
,"Excessive Force"
,"Exquisite Corpse"
,"Faction"
,"Factor One"
,"The Fair Sex"
,"Fatal Morgana"
,"Feindflug"
,"Fektion Fekler"
,"Fiction 8"
,"Fictional"
,"Filter"
,"Final Cut"
,"Fini Tribe"
,"Fishtank No. 9"
,"Flesh Field"
,"Flowerpot Men"
,"Flugsch√§del"
,"Force Dimension"
,"Ford Proco"
,"Forma Tadre"
,"The Fourth Man"
,"Fracture"
,"Fred"
,"Friends of Carlotta"
,"Front Line Assembly"
,"Front 242"
,"Funker Vogt"
,"Fusspils 11"
,"Fuze Box Machine"
,"The Galan Pixs"
,"Ganzheit"
,"Gaytron"
,"Genital A-Tech"
,"G.G.F.H."
,"Godheads"
,"God Is LSD"
,"God Module"
,"Good Courage"
,"Gracious Shades"
,"Greater Than One"
,"Gridlock"
,"Gruesome Twosome"
,"H"
,"Haloblack"
,"Hanzel & Gretyl"
,"Hate Dept."
,"Haujobb"
,"Havoc"
,"Headcrash"
,"Heavy Water Factory"
,"Hellbent"
,"Hellsau"
,"Hexedene"
,"Hilt"
,"H.M.B"
,"Hocico"
,"Hole"
,"Holocaust Theory"
,"Hope & Kirk"
,"H2O"
,"Hula"
,"Hyperdex-1-Sect"
,"Ian Sane"
,"Icon Of Coil"
,"Idiot Stare"
,"Image Transmission"
,"Imminent Starvation"
,"Imperative Reaction"
,"Implant Code"
,"Implant"
,"In Absentia"
,"Index"
,"Individual Totem"
,"Individual Industry"
,"Industrial Artz"
,"Industrial Heads"
,"Inertia"
,"Infact"
,"Inform√§tik"
,"Inscape"
,"Insekt"
,"Inside Treatment"
,"Insight 23"
,"In Sotto Voce"
,"Institute For The Criminally Insane"
,"Institute of Technology"
,"In Strict Confidence"
,"Interference"
,"Intermix"
,"Internal"
,"Invincible Spirit"
,"Ionic Vision"
,"Ipecac Loop"
,"Iron Lung Corporation"
,"IT"
,"Ivoux"
,"Jade 4 U"
,"Jagd Wild"
,"Jass"
,"Jihad"
,"Johnson Engineering Co."
,"Joined At The Head"
,"Jouissance"
,"Kalte Farben"
,"Kevorkian Death Cycle"
,"Praga Khan"
,"Killing Floor"
,"Kill Switch...Klick"
,"Richard H. Kirk"
,"The Klinik"
,"Klirrfaktor"
,"Klute"
,"KMFDM"
,"K-Nitrate"
,"Kode IV"
,"Konzept"
,"Kraftwerk"
,"Kramm"
,"Lab Animals"
,"Lame Immortelle"
,"Larceny"
,"Lassigue Bendthaus"
,"Last Delay"
,"Lead into Gold"
,"Leather Strip"
,"Keith LeBlanc"
,"Lesser"
,"Lights of Euphoria"
,"Limbo"
,"Liquid Sex Decay"
,"Llwybr Llaethog"
,"Lords of Acid"
,"Lost Image"
,"Lost Signal"
,"Luxt"
,"Machines of Loving Grace"
,"Mainesthai"
,"Maintenance Of Order"
,"Majestic"
,"Manapsara"
,"Manipulation"
,"Manufacture"
,"Martyr Colony"
,"Massiv In Mensch"
,"Master Program"
,"Mastertune"
,"Matrix"
,"Matter Of Fact"
,"Max M"
,"MC 900 Ft Jesus"
,"Meat Beat Manifesto"
,"Meathead"
,"Megadump"
,"Men 2nd"
,"Mentallo and the Fixer"
,"Mesh"
,"Metropolis"
,"Microchip League"
,"Mighty Force"
,"Boris Mikulic"
,"Mimic Mind"
,"Minister of Noise"
,"Ministry"
,"Moev"
,"Moksha"
,"Mono No Aware"
,"Monstrum Sepsis"
,"Morgue"
,"Morgue Mechanism"
,"Morpheus Sister"
,"Mortal Constraint"
,"Moskwa TV"
,"Museum of Devotion"
,"Mussolini Headkick"
,"Nautilus"
,"Necrofix"
,"Needle"
,"Needle Sharing"
,"Negative Format"
,"Negro Sex"
,"Neon Judgement"
,"Neo Tec"
,"Nerve Conflict"
,"Nerve Factor"
,"Network Access"
,"Netz"
,"Neural Network"
,"Neuroplague"
,"Neutronic"
,"New Mind"
,"New Order"
,"Newt"
,"Nigra Nebula"
,"Nine Inch Nails"
,"Nitzer Ebb"
,"Noise Box"
,"Noise Control"
,"Noise Process"
,"Noise Unit"
,"Noisex"
,"Nomenclatura"
,"Non-Aggression Pact"
,"Nothing Inside"
,"Nova State Conspiracy"
,"Noxious Emotion"
,"Numb"
,"Of Skin & Saliva"
,"Oil In The Eye"
,"Oneiroid Psychosis"
,"1000 Homo DJs"
,"Oomph!"
,"Operating Strategies"
,"Orange Sector"
,"Osofaux"
,"Out Out"
,"Overgament"
,"Overlords"
,"Page 12"
,"Pailhead"
,"Pain Emission"
,"Pain Station"
,"Pankow"
,"Papa Brittle"
,"Paracont"
,"Parade Ground"
,"Parade of Sinners"
,"Paranoid"
,"Paranomia"
,"Patchworks"
,"Pax"
,"Peace Love And Pitbulls"
,"Penal Colony"
,"Phallus Dei"
,"Philadelphia Five"
,"Pig"
,"Pinch Point"
,"Pitch Yarn Of Matter"
,"Plastic Assault"
,"Plastic Noise Experience"
,"Pluuto"
,"Poesie Noire"
,"Portion Control"
,"Pounce International"
,"Pouppee Fabrikk"
,"Prayer Tower"
,"Prick"
,"Project-X"
,"Pro-Tech"
,"Psychic Force"
,"Psychopomps"
,"P.T.P."
,"Pulse Legion"
,"Putrefy Factor 7"
,"Pygmy Children"
,"Pzycho Bitch"
,"Radioactive Goldfish"
,"Railgun"
,"Ravenous"
,"Razed In Black"
,"Re/Act"
,"Red Sekta"
,"Regenerator"
,"Remyl"
,"Retina"
,"Revolting Cocks"
,"Re|Work"
,"Ringtailed Snorter"
,"RKiK"
,"Robotiko Rejekto"
,"Run Level Zero"
,"Sabotage"
,"Scapa Flow"
,"Scarecrow"
,"Scar Tissue"
,"Schnitt Acht"
,"Seabound"
,"Second Communication"
,"Second Disease"
,"Second Skin"
,"Second Voice"
,"Sect"
,"Seelenkrank"
,"Serpents"
,"Seven Trees"
,"Severed Heads"
,"Shade Factory"
,"Shining"
,"Siechtum"
,"Sielwolf"
,"Signal 12"
,"Signal Aout 42"
,"Signs Ov Chaos"
,"Simbolo"
,"Single Gun Theory"
,"Sinister Attraction"
,"Sister Machine Gun"
,"16 Volt"
,"Skinny Puppy"
,"Skorbut"
,"Slave Unit"
,"Sleepwalk"
,"Sloppy Wrenchbody"
,"Smersh"
,"SMP"
,"Snog"
,"Snowy Red"
,"Society Burning"
,"Soil & Eclipse"
,"Solar Enemy"
,"Some More Crime"
,"Son of Sam"
,"Spahn Ranch"
,"Sphere Lazza"
,"Splatter Squall"
,"S.P.O.C.K."
,"Stash Krohl"
,"State Of Being"
,"State Orchestra"
,"Stendal Blast"
,"Stereotaxic Device"
,"Steril"
,"Mark Stewart"
,"STG"
,"Stin Scatzor"
,"Strategy"
,"Stromkern"
,"Suicide Commando"
,"Suiciety"
,"Swamp Terrorists"
,"Sweat Engine"
,"Synaesthesia"
,"Synapscape"
,"Syntax Error"
,"Syntec"
,"Tackhead"
,"Tankt"
,"Technogod"
,"Teknition"
,"Tekton Motor Corporation"
,"Telex"
,"Templebeat"
,"Terminal Choice"
,"Terminal White"
,"Terminal Sect"
,"Terror Against Terror"
,"TGT"
,"T.H.C."
,"T.H.D."
,"Think About Mutation"
,"Thinking Man"
,"Think Tank"
,"This Digital Ocean"
,"Thule"
,"Tilt!"
,"Tinfed"
,"Tit Wrench"
,"Tribantura"
,"Trumpets & Drums"
,"Trylok"
,"Tumor"
,"29 Died"
,"Ultraviolence"
,"Umo Detic"
,"Under the Noise"
,"Unheilig"
,"Unit 187"
,"Uprotor"
,"Urania"
,"U-Tek"
,"Vampire Rodents"
,"Vein Cage"
,"Velvet Acid Christ"
,"Johnny Violent"
,"Virus 23"
,"VNV Nation"
,"Vociferous Mutes"
,"Voi"
,"Voice of Destruction"
,"Voltage Control"
,"Vomito Negro"
,"Waiting For God"
,"The Weathermen"
,"Welle: Erdball"
,"Winterk√§lte"
,"WMTID"
,"Wumpscut"
,"X-Act"
,"X Marks The Pedwalk"
,"Xorcist"
,"XPQ-21"
,"X10"
,"XXX Atomic Toejam"
,"Xyphax"
,"Yeht Mae"
,"yelworC"
,"You Shriek"
,"Zero Defects"
,"A Chud Convention"
,"Aghast"
,"Ah Cama-Sotz"
,"Ain Soph"
,"Alio Die"
,"Allegory Chapel Ltd."
,"Allerseelen"
,"Alquimia"
,"AMM"
,"Ammer & Einheit"
,"Anal C*nt"
,"Anal Kitties"
,"Anal Solvent"
,"A.N.P."
,"The Anti Group"
,"Arcana"
,"Arcana"
,"Arcane Device"
,"Archon Satani"
,"Arkkon"
,"Art Barbeque"
,"A Spanner Thru Ma Beatbox"
,"Atomine Elektrine"
,"Atom Infant Incubator"
,"Attrition"
,"Autopsia"
,"Nigel Ayers & John Everall & Mick Harris"
,"Bad Sector"
,"Emil Beaulieau"
,"Big City Orchestra"
,"Bizarr Sex Trio"
,"Blackhouse"
,"Black Lung"
,"Blink Twice"
,"Borbetomagus"
,"Bourbonese Qualk"
,"Boy Dirt Car"
,"Glenn Branca"
,"Brighter Death Now"
,"Brise-Glace"
,"Justin Broadrick"
,"William S. Burroughs"
,"Cabaret Voltaire"
,"Can"
,"Carbon 14"
,"Chris Carter"
,"Caul"
,"Monte Cazazza"
,"C.C. Nova"
,"Chris and Cosey"
,"Chrome"
,"Cindytalk"
,"Clair Obscur"
,"Coil"
,"Condemek"
,"Con-Dom"
,"Consono"
,"Contagious Orgasm"
,"Controlled Bleeding"
,"Converter"
,"Coph Nia"
,"C.O.T.A."
,"Cranioclast"
,"Crash Worship ADRV"
,"Crawling With Tarts"
,"Crawl Unit"
,"C17"
,"C17H19NO3"
,"CTI"
,"Current 93"
,"Cyrnai"
,"D.D.A.A."
,"Dead Voices On Air"
,"Deca"
,"De Fabriek"
,"Delerium"
,"Delphium"
,"Desaccord Majeur"
,"Desiderii Marginis"
,"Deutsch Nepal"
,"Die Vorkriegszeit"
,"Dissecting Table"
,"Doubting Thomas"
,"John Duncan"
,"Each Dawn I Die"
,"F.M. Einheit"
,"Einst√ºrzende Neubauten"
,"Empirical Sleeping Consort"
,"Endura"
,"Esplendor Geometrico"
,"Etant Donnes"
,"Exterior Mirror"
,"Festula Mucosus"
,"Fetisch Park"
,"Final"
,"FM"
,"Foundation For Public Broadcasting"
,"400 Blows"
,"Diamanda Gal√°s"
,"General Strike"
,"Gerechtigkeits Liga"
,"GeroGeriGeGeGe"
,"G.L.O.D."
,"G* Park"
,"Gravitar"
,"Randy Greif"
,"Jeff Greinke"
,"Grey Wolves"
,"Hafler Trio"
,"Hanatarash"
,"Hands To"
,"Mick Harris & Martyn Bates"
,"The Haters"
,"Christoph Heemann"
,"H.N.A.S."
,"H√∂h & Current 93"
,"H√∂h"
,"Hole"
,"Ernst Horn"
,"Hula"
,"Human Head Transplant"
,"Hungry Ghosts"
,"Hunting Lodge"
,"Hybryds"
,"IAO Core"
,"Ichor"
,"Illusion of Safety"
,"Inanna"
,"In Blind Embrace"
,"Indicate"
,"In Slaughter Natives"
,"IRM"
,"Isolrubin BK"
,"Iugula-Thor"
,"Jack Or Jive"
,"Caroline K"
,"Karmanik"
,"Katharsis"
,"Richard H. Kirk"
,"The Klinik"
,"Thomas K√∂ner"
,"Konstruktivits"
,"Labradford"
,"Lab Report"
,"Lagowski"
,"Laibach"
,"Kirk Lake"
,"Alan Lamb"
,"Left Hand Right Hand"
,"Legion"
,"Paul Lemos & Joe Papa"
,"Paul Lemos"
,"Life Garden"
,"Lilith"
,"Loi Interceps"
,"Lull"
,"Lustmord"
,"Maeror Tri"
,"Main"
,"Stephen Mallinder"
,"Mandible Chatter"
,"Maschinenzimmer 412"
,"Master/Slave Relationship"
,"Matera"
,"Mauro Teho Teardo"
,"Maybe Mental"
,"M.B."
,"Meatyard"
,"Megaptera"
,"Memorandum"
,"Daniel Menche"
,"Mental Destruction"
,"Mental Measuretech"
,"Mesh"
,"Mimir"
,"Minimal Man"
,"Missing Foundation"
,"Mlada Fronta"
,"Chris Moriarty"
,"Morphogenesis"
,"Morthound"
,"Mortiis"
,"Multicide"
,"Munch"
,"Muslimgauze"
,"Mynox Layh"
,"Nada"
,"Nagamatzu"
,"Naked City"
,"Necrophorus"
,"Negativland"
,"Nightmare Lodge"
,"Nocturnal Emissions"
,"Non"
,"The Normal"
,"Not Breathing"
,"Nox"
,"K.K. Null"
,"Null & Plotkin"
,"Nurse With Wound"
,"Nux Vomica"
,"Omala"
,"Operation Mind Control"
,"Ophiolateria"
,"Ordo Equilibrio"
,"Organum"
,"Jim O Rourke"
,"Orphx"
,"John Oswald"
,"Pacific 231"
,"P.A.L"
,"Parca Pace"
,"P.B.K."
,"P. Children"
,"People Like Us"
,"PGR"
,"Phallus Dei"
,"Phauss"
,"James Plotkin"
,"Plotkin & Harris"
,"+ N"
,"Pointless Orchestra"
,"Popul Vuh"
,"Pornosect"
,"Genesis P Orridge"
,"Portion Control"
,"Premature Ejaculation"
,"Princess Dragon Mom"
,"Proiekt Hat"
,"P16D4"
,"Psychic TV"
,"Psychophysicist"
,"Psyclones"
,"Pump"
,"Raison d Etre"
,"Ramleh"
,"Rapoon"
,"Regard Extreme"
,"Residents"
,"Graeme Revell"
,"Rhythm and Noise"
,"Boyd Rice"
,"Robert Rich"
,"Steve Roach"
,"Runes Order"
,"Sanctum"
,"S.B.O.T.H.I."
,"Scanner"
,"Scattered Order"
,"Schamanen Circel"
,"Schnitzler & Thomasius"
,"Paul Sch√ºtze"
,"S-Core"
,"Scorn"
,"Seemen"
,"Severed Heads"
,"Elliott Sharp"
,"Sheephead"
,"Shinjuku Thief"
,"Shock Headed Peters"
,"Sigillum S"
,"Sirvix"
,"Sixth Comm"
,"Slap"
,"Sleep Chamber"
,"Slugbait"
,"Social Interiors"
,"Soma"
,"Sonar"
,"Sow"
,"SPK"
,"Sprung Aus den Wolken"
,"The State"
,"Stereotaxic Device"
,"Carl Stone"
,"Stone Glass Steel"
,"Strafe fur Rebellion"
,"Stratvm Terror"
,"Stress"
,"Sucking Chest Wound"
,"Sugarconnection"
,"Sutcliffe Jugend"
,"Swans"
,"Syllyk"
,"Systema"
,"T.A.C."
,"Tactile"
,"Tape Beatles"
,"Tear Garden"
,"Techno Animal"
,"Tekachi"
,"Telepherique"
,"Temps Perdu?"
,"Terminal Cheesecake"
,"Test Dept."
,"Thistle"
,"Throbbing Gristle"
,"Asmus Tietchens"
,"Tombstone"
,"Toop & Eastley"
,"Torture Chorus"
,"Trance"
,"Tribes of Neurot"
,"Tuu"
,"23 Skidoo"
,"Type Non"
,"Un Drame Musical Instantane"
,"Vacuum Tree Head"
,"Vasilisk"
,"Vidna Obmana"
,"Voice of Eye"
,"Vox Populi"
,"John Wall"
,"John Watermann"
,"Whitehouse"
,"White Stains"
,"Y-Ton-G"
,"Z ev"
,"John Zewizz"
,"Zoviet France"
,"Atmospheric"
,"Abecedarians"
,"A Certain Ratio"
,"A.C. Marias"
,"Barry Adamson"
,"Adorable"
,"Adult Fantasies"
,"Adult Net"
,"Air Miami"
,"Algebra Suicide"
,"An April March"
,"Anchorage"
,"And Also the Trees"
,"Annabelles Garden"
,"Anymore"
,"Apes of God"
,"Apparition"
,"A Primary Industry"
,"Arcanta"
,"Area"
,"A.R. Kane"
,"Arms of Someone New"
,"Aroma di Amore"
,"A Scanner Darkly"
,"Asylum Party"
,"Aurora VALUES(Sutra)"
,"Autumn Cathedral"
,"Autumn Fair"
,"Ave Maria Avida"
,"Babel 17"
,"Bailter Space"
,"Bark Psychosis"
,"Beautiful People Ltd."
,"Beautiful Pea Green Boat"
,"The Bel Am"
,"Bel Canto"
,"Belly"
,"Heidi Berry"
,"Bettie Serveert"
,"BFG"
,"Big Hard Excellent Fish"
,"Big Hat"
,"Blackbird"
,"Black Rose"
,"Black Sea"
,"Black Tape For a Blue Girl"
,"Blade Fetish"
,"Bleach"
,"Bleak"
,"Bleeding Like Mine"
,"Blind Mr. Jones"
,"Blue Blue Blue"
,"Simon Bonney"
,"Bowery Electric"
,"Breathless"
,"The Breath Of Life"
,"The Breeders"
,"Michael Brook"
,"Harold Budd"
,"Bulgarian Voices"
,"Bushido"
,"Caterwaul"
,"Catherine Wheel"
,"Cello"
,"Chameleons"
,"Chandeen"
,"Chapterhouse"
,"The Charlottes"
,"Cherche Lune"
,"Clair Obscur"
,"Closedown"
,"Cocteau Twins"
,"CoEx"
,"Collection D Arnell Andrea"
,"Common Language"
,"Congo Norvell"
,"Cranes"
,"Crime & The City Solution"
,"Cure"
,"The Curtain Society"
,"Curve"
,"Dark Arts"
,"Dark Orange"
,"Dead Can Dance"
,"Death in June"
,"Deception Bay"
,"Delerium"
,"Difference Engine"
,"Dif Juz"
,"Disco Inferno"
,"Dominion"
,"Anna Domino"
,"Doris"
,"The Dreamside"
,"Drowning Pool"
,"Durutti Column"
,"The Ecstasy of Saint Theresa"
,"Eden"
,"Electric Company"
,"Elijah s Mantle"
,"Elysium"
,"Emerald Vein"
,"End Of Orgy"
,"Evergreen Dazed"
,"Eyeless In Gaza"
,"Felt"
,"Fire & Ice"
,"For Against"
,"Fourwaycross"
,"Frazier Chorus"
,"Frolic"
,"The Frozen Autumn"
,"Fuel"
,"Funeral Party"
,"Galaxie 500"
,"Lisa Gerrard"
,"Lisa Gerrard & Pieter Bourke"
,"Bruce Gilbert"
,"Glee Club"
,"Glove"
,"God Said"
,"Hair & Skin Trading Co."
,"Half String"
,"Halou"
,"Handful of Snowdrops"
,"Heart Throbs"
,"Heavenly Bodies"
,"Kristin Hersh"
,"He Said"
,"Hex"
,"Hex Rx"
,"His Name is Alive"
,"Hooverphonic"
,"The Hope Blister"
,"Horizon 222"
,"House of Love"
,"Hover"
,"Human Drama"
,"Ikon"
,"Ildfrost"
,"Insides"
,"In the Distance"
,"In the Nursery"
,"Invaders of the Heart"
,"Jaramar"
,"Johanna s House of Glamour"
,"Joy Division"
,"Judgement of Paris"
,"Edward Ka-Spel"
,"Kid Congo"
,"Kirlian Camera"
,"Kitchens of Distinction"
,"Kosova Republike"
,"La Floa Maldita"
,"Laika"
,"Anita Lane"
,"Lanterna"
,"Legendary Pink Dots"
,"Les Jumeaux"
,"Little Nemo"
,"Loop"
,"Love Is Colder Than Death"
,"LoveLiesCrushing"
,"Love Spirals Downwards"
,"Low"
,"Lowlife"
,"Lowsunday"
,"Lucie Cries"
,"Lush"
,"Lycia"
,"Magenta"
,"Main"
,"Manic P."
,"Marnie"
,"Mazzy Star"
,"Loreena McKennit"
,"Sarah McLachlan"
,"Medicine"
,"Mellonta Tauta"
,"Merlons Of Nehemiah"
,"The Millions"
,"Minimal Compact"
,"Mira"
,"Miranda Sex Garden"
,"Mistle Thrush"
,"Modern English"
,"Mojave 3"
,"M-1 Alternative"
,"The Moon Seven Times"
,"Moonshake"
,"Moose"
,"Mumbles"
,"My Bloody Valentine"
,"National Razor"
,"Colin Newman"
,"The New York Room"
,"Ninth Circle"
,"Nouvelles Lectures Cosmopolites"
,"Orange"
,"Ordo Equitum Solis"
,"Ostia"
,"O Yuki Conjugate"
,"Pale Saints"
,"Pelican Daughters"
,"Brendan Perry"
,"Pink Industry"
,"Pixies"
,"Bill Pritchard"
,"Pupilla"
,"Qntal"
,"Raison d Etre"
,"Rajna"
,"Recoil"
,"Red House Painters"
,"Red Temple Spirits"
,"Requiem in White"
,"Revolutionary Army of the Infant Jesus"
,"Richenel"
,"Ride"
,"Rise and Fall of a Decade"
,"Rosa Mota"
,"Rose of Avalanche"
,"Rosewater Elizabeth"
,"Royal Family and the Poor"
,"Sad Lovers and Giants"
,"St. Etienne"
,"Savage Republic"
,"Scala"
,"Scenic"
,"Scheer"
,"Sea Of Tranquility"
,"Section 25"
,"Seefeel"
,"Shelleyan Orphan"
,"Sianspheric"
,"Siddal"
,"Skin"
,"Skinner Box"
,"Sky Cries Mary"
,"Sleeping Dogs Wake"
,"Slowdive"
,"Snowblind"
,"Sofia Run"
,"The Soil Bleeds Black"
,"Sol Invictus"
,"Sonic Boom"
,"Soul Brothers"
,"Soul Whirling Somewhere"
,"Spacemen 3"
,"Speaking Silence"
,"Spectrum"
,"Malka Spigel"
,"Spirea X"
,"Spiritualized"
,"Stay Frightened"
,"Stereolab"
,"Stoa"
,"Strange Boutique"
,"The Sundays"
,"Sun God"
,"Swallow"
,"Swandive"
,"Swans"
,"David Sylvian"
,"Tear Garden"
,"Tel Basta"
,"Terrace Of Memories"
,"That Dog"
,"Thelema"
,"These Immortal Souls"
,"The The"
,"This Ascension"
,"This Mortal Coil"
,"This Scarlet Train"
,"Thrive"
,"Throwing Muses"
,"Trance To The Sun"
,"Trisomie 21"
,"Ultra Vivid Scene"
,"Underground Lovers"
,"Unto Ashes"
,"Vazz"
,"Voltaire"
,"What? Noise"
,"Will"
,"Wire"
,"The Wolfgang Press"
,"Wonder"
,"Xymox"
,"Gothic/Darkwave"
,"After Darkness"
,"Alien Sex Fiend"
,"All About Eve"
,"Altered States"
,"Andi Sex Gang"
,"Angina Pectoris"
,"Apocalypse Theatre"
,"Arcana Obscura"
,"Arts And Decay"
,"Daniel Ash"
,"Ataraxia"
,"Atrocity"
,"Autumn"
,"Bauhaus"
,"Big Electric Cat"
,"Birthday Party"
,"The Bolshoi"
,"The Cain Principle"
,"Camerata Mediolanense"
,"Cancer Barrack"
,"Canticum Funebris"
,"Car Crash International"
,"Catastrophe Ballet"
,"Catherine s Cathedral"
,"Nick Cave"
,"The Changelings"
,"Children On Stun"
,"Christian Death"
,"Corpus Delicti"
,"Cradle of Spoil"
,"Creaming Jesus"
,"The Creatures"
,"Cries Of Tammuz"
,"The Cruxshadows"
,"The Cult"
,"The Damned"
,"Danse Society"
,"Dark Side Cowboys"
,"Das Ich"
,"Dawn Fades"
,"Death in June"
,"The Deep Eynde"
,"Deine Lakaien"
,"Gitane Demone"
,"Der Prager Handgriff"
,"Diary Of Dreams"
,"Die My Darling"
,"Dorsetshire"
,"Dracul"
,"Dreadful Shadows"
,"Dronning Maud Land"
,"Drown For Resurrection"
,"Emeralde Fear"
,"Endless"
,"Endraum"
,"Engelsstaub"
,"The Eternal Afflict"
,"Every New Dead Ghost"
,"Executive Slacks"
,"Fading Colours"
,"Faith And Disease"
,"Faith And the Muse"
,"Fields of the Nephilim"
,"Fortification 55"
,"45 Grave"
,"Funhouse"
,"Diamanda Gal√°s"
,"The Garden Of Delight"
,"Gargoyle Sox"
,"Ghost Dance"
,"Ghosting"
,"Girls Under Glass"
,"Goethes Erben"
,"House of Usher"
,"In Faith"
,"Inkubus Sukkubus"
,"In My Rosary"
,"Kastrierte Philosophen"
,"Kill Sister Kill"
,"Kommunity FK"
,"The Last Dance"
,"Law Of The Dawn"
,"Lestat"
,"London After Midnight"
,"Love & Rockets"
,"Love Like Blood"
,"The Machine In The Garden"
,"Malaise"
,"Malign"
,"March Violets"
,"The Marionettes"
,"Masochistic Religion"
,"Medicine Rain"
,"Mephisto Walz"
,"The Merry Thoughts"
,"Midnight Configuration"
,"The Mission"
,"The Morendoes"
,"Mors Syphilitica"
,"Peter Murphy"
,"Nature And Organisation"
,"Neither/Neither World"
,"Neuzeit Syndrom"
,"New Model Army"
,"Nosferatu"
,"Eva O. Halo Experience"
,"Panic on the Titanic"
,"Paralysed Age"
,"Pierrepoint"
,"Placebo Effect"
,"Play Dead"
,"Project Pitchfork"
,"The Prophetess"
,"James Ray"
,"The Razor Skyline"
,"R.E.C."
,"Red Lorry Yellow Lorry"
,"Return To Khafji"
,"Revolution By Night"
,"Rosetta Stone"
,"Salvation"
,"Screams For Tina"
,"Second Skin"
,"Secret Discovery"
,"Seraphim Shock"
,"Sex Gang Children"
,"Shadow Light"
,"Shadow Project"
,"Shine"
,"The Shroud"
,"Silke Bischoff"
,"Siouxsie and the Banshees"
,"The Sisterhood"
,"Sisters of Mercy"
,"Sixth Comm"
,"Skeletal Family"
,"Sleeping Dogs Wake"
,"Sopor Aeternus"
,"Southern Death Cult"
,"Specimen"
,"Stone 588"
,"Sub Version"
,"Sunshine Blind"
,"Super Heroines"
,"Suspiria"
,"Swans Of Avon"
,"Switchblade Symphony"
,"Tatmotiv Angst"
,"Tears Of Passion"
,"Tones on Tail"
,"The Tors of Dartmoor"
,"Trauma"
,"Trial"
,"Two Witches"
,"UK Decay"
,"Umbra Et Imago"
,"Usherhouse"
,"Venus Walk"
,"Virgin Prunes"
,"The Wake"
,"Wench"
,"Rozz Williams"
,"The Winter Chapter"
,"Xmal Deutschland"
,"Beborn Beton"
,"Cell"
,"Chiasm"
,"Cosmicity"
,"De/Vision"
,"Echo Image"
,"The Echoing Green"
,"Edenfeld"
,"Equatronic"
,"Estatuas de Sol"
,"Infam"
,"Intact"
,"Intervox"
,"Iris"
,"Lederer"
,"Melotron"
,"Neuroactive"
,"Neuroticfish"
,"New Concept"
,"No Comment"
,"No Decay"
,"Sarah Noxx"
,"ObscVALUES(y)re"
,"Philtron"
,"Point Of View"
,"Psyche"
,"Rational Youth"
,"Reflected Image"
,"Shades Of Grey"
,"Silent Promises"
,"Squareheads"
,"Sugartax"
,"Technoir"
,"Trays"
,"Wolfsheim"
,"Acrostichon"
,"Amorphis"
,"Anathema"
,"Atrocity"
,"At The Gates"
,"Autopsy"
,"Baphomet"
,"Blohole"
,"Bolt Thrower"
,"Brujeria"
,"Brutal Truth"
,"Cadaver"
,"Cannibal Corpse"
,"Carcass"
,"Carnage"
,"Cathedral"
,"Confessor"
,"Convulse"
,"Corrosion of Conformity"
,"Cynic"
,"Darkthrone"
,"Death"
,"Deceased"
,"Disciples Of Power"
,"Disembowelment"
,"Disincarnate"
,"Disrupt"
,"Entombed"
,"Exit-13"
,"Filthy Christians"
,"General Surgery"
,"Gorguts"
,"Hellbastard"
,"Heresy"
,"Immolation"
,"Impaler"
,"Incantation"
,"Intense Degree"
,"Lawnmower Deth"
,"Life Of Agony"
,"Macabre"
,"Malevolent Creation"
,"Meshuggah"
,"Morbid Angel"
,"Mortal God"
,"Mortician"
,"My Dying Bride"
,"Narcolepsy"
,"Nocturnus"
,"Pantera"
,"Paradise Lost"
,"Pentagram"
,"Phobia"
,"Pungent Stench"
,"Repulsion"
,"Sepultura"
,"Sick Of It All"
,"Sleep"
,"Sore Throat"
,"Sorrow"
,"Soulstorm"
,"Spazztic Blurr"
,"Suffocation"
,"Terrorizer"
,"Traumatic Voyage"
,"Unseen Terror"
,"Vital Remains"
,"A Guy Called Gerald"
,"Altern 8"
,"Amorphous Androgynous"
,"Aphex Twin"
,"Arecibo"
,"Atari Teenage Riot"
,"Autechre"
,"The Black Dog"
,"Boytronic"
,"Caresse & Sickmob"
,"Chaos Face"
,"Eat Static"
,"808 State"
,"Eon"
,"Future Sound of London"
,"Gravity"
,"GTO"
,"Hard Corps"
,"Heavenly Music Corporation"
,"Horizon 222"
,"Juno Reactor"
,"Kl√§nge"
,"KLF"
,"Koxbox"
,"L.A. Style"
,"La Tour"
,"L.F.O."
,"Moby"
,"N-Joi"
,"The Orb"
,"Orbital"
,"Polygon Window"
,"The Prodigy"
,"Psychick Warriors ov Gaia"
,"Psychic TV"
,"Psykosonik"
,"Renegade Soundwave"
,"Sector"
,"Seefeel"
,"The Shamen"
,"Sheep On Drugs"
,"68000"
,"Spacetime Continuum"
,"Subitto"
,"Sweet Exorcist"
,"T99"
,"Ultramarine"
,"Ultraviolet Catastrophe"
,"Xol Dog 400"
,"1000 Homo Djs"
,"Acumen Nation"
,"Aghast View"
,"Alien Sex Fiend"
,"Anax Imperator"
,"Apoptygma Berzerk"
,"Assemblage 23"
,"Bile"
,"Blixa Bargeld"
,"Cabaret Voltaire"
,"cEVIN Key"
,"Chris & Cosey"
,"Chris Connelly"
,"Chrome"
,"Clock DVA"
,"Coil"
,"Consolidated"
,"Controlled Bleeding"
,"Covenant"
,"Cultural Amnesia"
,"Current 93"
,"D.A.F."
,"Dead Voices on Air"
,"Decoded Fedback"
,"Delerium"
,"Die Form"
,"Die Warzau"
,"din_fiv"
,"Dissecting Table"
,"Download"
,"Einst√ºrzende Neubauten"
,"Electric Hellfire Club"
,"Evils Toy"
,"Fear Factory"
,"Filter"
,"Foetus"
,"Front 242"
,"Front Line Assembly"
,"Funker Vogt"
,"Genesis P. Orridge"
,"God Lives Underwater"
,"Gravity Kills"
,"Haujobb"
,"Hocico"
,"Icon of Coil"
,"Information Society VALUES(only on Dont be Afraid)"
,"Intermix"
,"KMFDM"
,"kidneythieves"
,"Kraftwerk"
,"Laibach"
,"The Legendary Pink Dots"
,"Marilyn Manson"
,"Meat Beat Manifesto"
,"Mentallo & The Fixer"
,"Ministry"
,"Mortiis"
,"My Life With the Thrill Kill Kult"
,"Negativland"
,"Nine Inch Nails"
,"Nitzer Ebb"
,"Noise Unit"
,"Noisex"
,"Numb"
,"Nurse With Wound"
,"ohGr"
,"P.A.L."
,"Pailhead"
,"Peter Christopherson"
,"Pig"
,"Pigface"
,"Pitchshifter"
,"Pop Will Eat Itself"
,"Project Pitchfork"
,"Psychic TV"
,"Psychopomps"
,"Pygmy Children"
,"Rammstein"
,"Razed In Black"
,"Renegade Soundwave"
,"Revolting Cocks"
,"Rorschach Test"
,"Severed Heads"
,"Sister Machine Gun"
,"Sheep on Drugs"
,"Skinny Puppy"
,"Snog"
,"SMP"
,"Spahn Ranch"
,"SPK"
,"Stabbing Westward"
,"Suicide Commando"
,"Swans"
,"Test Dept."
,"THD"
,"Throbbing Gristle"
,"Trent Reznor"
,"Velvet Acid Christ"
,"VNV Nation"
,"Whitehouse"
,"Wolfsheim"
,"Wumpscut"
,"Young Gods"
,"X Marks The Pedwalk"
,"Zoviet France"
,"Throbbing Gristle"
,"Ministry"
,"Cabaret Voltaire"
,"Skinny Puppy"
,"Front 242"
,"Einst√ºrzende Neubauten"
,"KMFDM"
,"Nitzer Ebb"
,"Coil"
,"Marilyn Manson"
,"Killing Joke"
,"Foetus"
,"Rob Zombie & White Zombie"
,"Test Dept."
,"Monte Cazazza"
,"Front Line Assembly"
,"Chrome"
,"Die Krupps"
,"Meat Beat Manifesto"
,"Whitehouse"
,"Fear Factor"
,"Clock DVA"
,"My Life With The Thrill Kill Kult"
,"Filter"
,"Boyd Rice"
,"Godflesh"
,"Swans"
,"Z EV"
,"Rammstein"
,"Deutsch-Amerikanische Freundschaft"
,"Lustmord"
,"SPK"
,"Psychic TV"
,"Controlled Bleeding"
,"Nurse with Wound"
,"Tackhead"
,"Portion Control"
,"Stabbing Westward"
,"Laibach"
,"Wumpscut"
,"Gravity Kills"
,"Le√¶ther Strip"
,"23 Skidoo"
,"Chris & Cosey"
,"Severed Heads"
,"Nocturnal Emissions"
,"Haujobb"
,"Death in June"
,"Pigface"
,"Renegade Soundwave"
,"Current 93"
,"Zoviet France"
,"Young Gods"
,"Die Warzau"
,"Legendary Pink Dots"
,"Armageddon Dildos"
,"Electric Hellfire Club"
,"Revolting Cocks"
,"Hafler Trio"
,"Pitchshifter"
,"Chris Connelly"
,"The Grey Wolves"
,"VNV Nation"
,"Static-X"
,"Lab Report"
,"Chemlab"
,"The Neon Judgement"
,"Leather Nun"
,"Funker Vogt"
,"Mindless Self Indulgence"
,"Attrition"
,"Sister Machine Gun"
,"Combichrist"
,"X-Marks the Pedwalk"
,"Bile"
,"Pig"
,"A Split Second"
,"Powerman 5000"
,"Bigod 20"
,"Machines of Loving Grace"
,"Gary Clail"
,"And One"
,"16 Volt"
,"Maurizio Bianchi"
,"Cubanate"
,"Lilith"
,"Download"
,"√†;GRUMH..."
,"Orgy"
,"Dope"
,"Velvet Acid Christ"
,"Deutsch Nepal"
,"Gridlock"
,"Black Lung"
,"Dive"
,"Esplendor Geometrico"
,"Sol Invictus"
,"Noisex"
,"Brighter Death Now"
,"Agatha Christie"
,"Alien Sex Fiend"
,"All About Eve"
,"All Gone Dead"
,"And Also The Trees"
,"Andi Sexgang"
,"Astrovamps"
,"Ausgang"
,"The Awakening"
,"Balaam and the Angel"
,"Bauhaus"
,"Belfegore"
,"Bella Morte"
,"Big Electric Cat"
,"The Birthday Party"
,"Bitter Grace"
,"Black Ice"
,"The Bolshoi"
,"Caelum Bliss"
,"Cauda Pavonis"
,"Children on Stun"
,"Christian Death[20]"
,"The Church"
,"Clan of Xymox"
,"Corpus Delicti"
,"Cocteau Twins"
,"Cranes"
,"Cuddly Toys"
,"The Cult"
,"The Cure"
,"Daimonion"
,"The Damned"
,"The Danse Society"
,"Dead Artist Syndrome"
,"Dead Can Dance"
,"Diary of Dreams"
,"Diva Destruction"
,"Dominion"
,"Dommin"
,"Eva O"
,"Evanescence"
,"Epica"
,"Faith and the Muse"
,"Fields of the Nephilim"
,"Frank the Baptist"
,"Gene Loves Jezebel"
,"Ghost Dance"
,"Gitane Demone"
,"Gloria Mundi"
,"Hatesex"
,"Human Drama"
,"Ikon"
,"James Ray & The Performance"
,"James Rays Gangwar"
,"Joy Division"
,"KASMs"
,"Kommunity FK"
,"The Last Dance"
,"The Last Days of Jesus"
,"Libitina"
,"London After Midnight"
,"The Lords of the New Church"
,"Love And Rockets"
,"Love Like Blood"
,"Lycia"
,"The Machine in the Garden"
,"The March Violets"
,"Mephisto Walz"
,"The Merry Thoughts"
,"Miranda Sex Garden"
,"The Mission"
,"Mistle Thrush"
,"Mizar"
,"Mors Syphilitica"
,"Musta Paraati"
,"The Naked and the Dead"
,"Nick Cave & the Bad Seeds"
,"Nosferatu"
,"Paralysed Age"
,"Pink Turns Blue"
,"Play Dead"
,"Qntal"
,"Radio Werewolf"
,"Red Lorry Yellow Lorry"
,"Rhea s Obsession"
,"Rosetta Stone"
,"Rozz Williams"
,"Russian Love"
,"Screams For Tina"
,"Second Skin"
,"Sex Gang Children"
,"Shadow Project"
,"The Shroud"
,"Siouxsie and the Banshees"
,"The Sisterhood"
,"The Sisters of Mercy"
,"Skeletal Family"
,"Solemn Novena"
,"Southern Death Cult"
,"Specimen"
,"Star Industry"
,"Super Heroines"
,"Suspiria"
,"Switchblade Symphony"
,"Theatre of Hate"
,"Theatre of Ice"
,"This Mortal Coil"
,"Tones on Tail"
,"Trivalia"
,"Two Witche"
,"13 Candles"
,"13th Chime"
,"13 Knots"
,"13th Moon"
,"13th Sky"
,"13 Tombs"
,"1919"
,"26 Tears"
,"34 Vampires"
,"45 Grave"
,"99 Stellavista"
,"Acid Bats"
,"Actifed"
,"Adams Family"
,"Address Unknown"
,"Adoration"
,"Advent Sleep"
,"After Dusk"
,"Age Of Heaven"
,"Ahr√°yeph"
,"Aidons la Norv√®ge"
,"Alan Woxx"
,"Alaydha"
,"Alice On Speed"
,"Alien Sex Fiend"
,"All Gone Dead"
,"All Living Fear"
,"Altered States"
,"Am Tag Unter Null"
,"Ancestry"
,"And Also The Trees"
,"Andi Hayes"
,"Anfisbena"
,"Angel And The Badman"
,"Antiworld"
,"A Place To Bury Strangers"
,"Apocalypse Theatre"
,"Arch√©typo"
,"Arc Gotic"
,"Artica"
,"Arts Of Erebus"
,"Asmodi Bizarr"
,"A Spectre Is Haunting Europe"
,"Astrovamps"
,"Asylum Party"
,"Asylum XIII"
,"Atomic Neon"
,"Atomic Spider"
,"Audra"
,"Ausgang"
,"Autumn"
,"Autumn Cathedral"
,"Autumn Of North"
,"Avant-Garde"
,"Avaritia"
,"Awakening"
,"Baby Shower"
,"Balaam And The Angel"
,"Bat Attakk"
,"Batcave 13"
,"Bauhaus"
,"Batzz In The Belfry"
,"Beauty For Ashes"
,"Beauty Of Gemina"
,"Belfegore"
,"BellINSERT INTO bands VALUES( Book And Candle"
,"Bellmer Dolls"
,"Bells Of Soul"
,"Bell Tower Bats"
,"Beryl Beloved"
,"Beyond The Wall Of Sleep"
,"Big Electric Cat"
,"Birthday Party"
,"Bitter Grace"
,"Bizarre Orkeztra"
,"Black Atmosphere"
,"Black Chanterelle"
,"Black Dolls"
,"Black Ice"
,"Blacklist"
,"Black RosesINSERT INTO bands VALUES( Poetry & Death"
,"Blessure Grave"
,"Blood And Roses"
,"Bloody Dead And Sexy"
,"Blue Cross"
,"Body Electric"
,"Bohemien"
,"Bolshoi"
,"Bomb Party"
,"Bonapartes"
,"Bone Orchard"
,"Born For Bliss"
,"Breathing Of Bones"
,"Breath Of Life"
,"Brickbats"
,"Brillig"
,"Brotherhood Of Pagans"
,"Burning Face"
,"Burning Gates"
,"Burning Image"
,"Cadillacs And Cadavers"
,"Cadra Ash"
,"Calling Dead Red Roses"
,"Cancer Barrack"
,"Capela Das Almas"
,"Carcrash International"
,"Castrati"
,"Casual Sanity"
,"Catastrophe Ballet"
,"Caves"
,"Cemetary Girlz"
,"Cemetery Whispers"
,"Chants Of Maldoror"
,"Chapel Of Thieves"
,"Charlottes Shadow"
,"Children On Stun"
,"Children s Zoo"
,"Christabel Dreams"
,"Christian Death"
,"Christ Vs. Warhol"
,"Chrysalis Morass"
,"Cinema Strange"
,"Clair Obscur"
,"Clan Of Xymox"
,"Coffinettes"
,"Cold Metal"
,"Corpus Delicti"
,"Council Of Days"
,"Counting The Mad"
,"Craft"
,"Crush Violets"
,"Crucifix Nocturnal Christians"
,"Cryscendo"
,"Cure"
,"Cured"
,"Curiosity"
,"Curious"
,"Curse Of The Vampire"
,"Cyan Revue"
,"Cyteres"
,"DA!"
,"Dada Dumdums"
,"Damned"
,"Dance"
,"Dancing Golem"
,"Daniel Colletti"
,"Danse Society"
,"Dark"
,"Darkness Visible"
,"Dark Orange"
,"Dark Side Cowboys"
,"Dark Theater"
,"Darlings"
,"Date At Midnight"
,"Daughters of Bristol"
,"Dawn Of Oblivion"
,"Days Are Nights"
,"Dead Artist Syndrome"
,"Deadchovsky"
,"Deadfly Ensemble"
,"Dead Guitars"
,"Dead Sea Surfers"
,"Dead Souls Rising"
,"Deafear"
,"Dearest Death"
,"Deathcamp Project"
,"Death Party"
,"Death Ride 69"
,"Decadent Circus"
,"Decima Victima"
,"Deep Eynde"
,"Demian Ashes"
,"D√©raison Noire"
,"Desmo Donte"
,"De Volanges"
,"Die Laughing"
,"Dies Irae"
,"Dies Irae"
,"Dirge Carolers"
,"Disjecta Membra"
,"Diva Destruction"
,"Doppelg√§nger"
,"Drama Of The Spheres"
,"Dr. Arthur Krause"
,"Dream Disciples"
,"Dreamspiral"
,"DreadINSERT INTO bands VALUES( The"
,"Dreadful Shadows"
,"Dronning Maud Land"
,"Droserae"
,"Drowning Season"
,"Eat Your Make-Up"
,"Ecos D‚ÄôAlma"
,"Eden House"
,"Eighth Plague"
,"El Clan"
,"Elegia"
,"Elegy Of Madeline"
,"Elusive"
,"Elvira And The Bats"
,"Emma Conquest"
,"Empire Hideous"
,"End Of Data"
,"Entertainment"
,"Erato"
,"Espiritus Xelene"
,"Eternal Chapter"
,"Eternal Fall"
,"Euroshima"
,"Eva"
,"Eva O Halo Experience"
,"Every New Dead Ghost"
,"Evil Speaks"
,"Exedra"
,"Exit To Eden"
,"Experiment Perilous"
,"Ex-VoTo"
,"Eyaculacion Post Mortem"
,"Eye"
,"Faces Of Sarah"
,"Faith And The Muse"
,"Fallacious World"
,"Fallen Apart"
,"Falling Janus"
,"False Faces"
,"Fangs On Fur"
,"Fear Cult"
,"Fear Of The Storm"
,"Feeding Fingers"
,"Fields Of The Nephilim"
,"Fixion"
,"Flagelo Cl√©riga"
,"Flesh EatersINSERT INTO bands VALUES( The"
,"Flir"
,"Flowers Of Romance"
,"Flowers Of Sacrifice"
,"Flowers Of The Past"
,"Forced Oscillations"
,"FormFleisch"
,"Frank The Baptist"
,"Frozen Autumn"
,"Funhouse"
,"Fur Bible"
,"Garden Of Delight"
,"Gar√ßons Coiffeurs"
,"Gargoyle Sox"
,"G√§rten Kirkh√∂f"
,"Gene Loves Jezebel"
,"Geschlecht Akt"
,"Gestalt"
,"Ghost Dance"
,"Ghost Of Lemora"
,"Giardino Violetto"
,"Gloria Mundi"
,"Goat Of Bethlehem"
,"Golden Apes"
,"Gorgonas"
,"G√∂tterd√§mmerung"
,"Grassby And Walker"
,"Graven Scars"
,"Graveyard Bats"
,"Graveyardz"
,"Grooving In Green"
,"Grotesque Sexuality"
,"Guilty Strangers"
,"Hall Of Souls"
,"Handful Of Snowdrops"
,"Hapalochlaena_Maculosa"
,"Happy Cadavres"
,"Happy Haus"
,"Hatesex"
,"H-Bomb White Noise"
,"Hearts Fail"
,"His Electro Blue Voice"
,"Holy Blood"
,"Holy Cow"
,"Horatii"
,"House Of Usher"
,"Human Disease"
,"Human Drama"
,"Hysteric Helen"
,"H. Zombie"
,"Igreja Do Sexo"
,"IKON"
,"Il Giardino Violetto"
,"Iloy"
,"Imaginary Walls"
,"In Excelsis"
,"In Grave"
,"Inkubus Sukkubus"
,"In Loving Memory"
,"Into The Abyss"
,"Isolation Ward"
,"Jacquy Bitch"
,"Jerusalem Syndrome"
,"Jesus Manson"
,"Joy Disaster"
,"Joy Division"
,"Judith"
,"Katzenjammer Kabarett"
,"Killing Witches"
,"Kill Sister Kill"
,"Kindred Spirits"
,"Kiss The Blade"
,"Kitchen And The Plastic Spoons"
,"Kommunity FK"
,"Kontakt 46"
,"Knutz"
,"Krakow Kasanovas"
,"KUKL"
,"La Calle Morgue"
,"Lady Besery s Garden"
,"Lahka Muza"
,"La Peste Negra"
,"Last Cry"
,"Last Dance"
,"Last Days Of Jesus"
,"Laughing Mothers"
,"La Voz De Tus Ausentes"
,"Legion"
,"L Enfance √âternelle"
,"Les Ma√Ætres"
,"Les Modules Etranges"
,"Lestat"
,"Leichenliebe"
,"Le Vene Di Lucretia"
,"Limbo"
,"L‚Äô Insignifiante Morte"
,"London After Midnight"
,"Lords Of The New Church"
,"Los Carniceros Del Norte"
,"Los Paralitikos"
,"Love Like Blood"
,"Love Infernal"
,"Love`s Labour`s Lost"
,"Lucie Cries"
,"Lucretia"
,"Luiza Fria"
,"Lycia"
,"Lyncelia"
,"Madame Edwarda"
,"Madre Del Vizio"
,"Mailuna"
,"Malaise"
,"Malochia"
,"Mansion 1313"
,"Marchesa Casati"
,"March Violets,"
,"Marionettes"
,"Mask For"
,"Martyr Whore"
,"Masochistic Religion"
,"Mekrokiev"
,"Mephisto Walz"
,"Merciful Nuns"
,"Meridian"
,"Merry Thoughts"
,"Midnight Call"
,"Miguel And The Living Dead"
,"Militia Christi"
,"Miranda Sex Garden"
,"Miserylab"
,"Mission"
,"Modern Creatures"
,"Momento Mori"
,"Monozid"
,"Morbid Poetry"
,"Mt. Sims"
,"Mumbles"
,"Mundtot"
,"Murder At The Registry"
,"Murnau‚Äôs Playhouse"
,"Musta Paraati"
,"Naughty Zombies"
,"Naked And The Dead"
,"Naked Masks"
,"Neon"
,"Neon Dream"
,"Nervous Choir"
,"Neurotic Doll"
,"Neva"
,"New Days Delay"
,"New Thrill Parade"
,"New Zero God"
,"NFD"
,"Nietzsche s Bitch"
,"Nightchild"
,"Nightmoves"
,"NightPorter"
,"Noctivagus"
,"Noctule Sorix"
,"Noone I Know"
,"Norma Loy"
,"Nosferatu"
,"No Tears"
,"Novocaine Mausoleum"
,"Ochrana"
,"Of A Mesh"
,"Oltretomba"
,"Opium Dream Estate"
,"Ordeal By Fire"
,"Orquideas Francesas"
,"Ostia"
,"Other Voices"
,"Oxsana Prism"
,"Par√°lisis Permanente"
,"Paralysed Age"
,"Parchment Prayer"
,"Passion Noire"
,"Passion Play"
,"Passions Mortelles"
,"Pauvre Maltea"
,"Peeling Grey"
,"Phaida"
,"Phantasmagoria"
,"Phantom Bertha"
,"Phantom Limbs"
,"Phantom Vision"
,"Pink Turns Blue"
,"Pins And Needles"
,"Pitchipoii"
,"Plague"
,"Plastique Noir"
,"Play Dead"
,"Plush Insane"
,"Pornografia"
,"PretentiousINSERT INTO bands VALUES( Moi?"
,"Primal Danse"
,"Projekt Krummen Mauern"
,"Projeto Renfield"
,"Prophetess"
,"Proximate Force"
,"Psuka√Ø"
,"Psychosurgery"
,"Quarzo Nero"
,"Queens Of Mescaline"
,"Quidam"
,"Rabies"
,"Radio Scarlet"
,"Radio Werewolf"
,"Ravensdiner"
,"Readership Hostile"
,"Rebel Christening"
,"Redemption"
,"Red Lorry Yellow Lorry"
,"Red Lipstick Death"
,"Red Temple Spirits"
,"Red Wedding"
,"Regenzeit"
,"Remain In Silence"
,"Remembrance"
,"Reptyle"
,"Requiem In White"
,"Return To Khaf ji"
,"Revenge Of Nephthys"
,"Rhombus"
,"Romance"
,"Rosa Crvx"
,"Rose Of Avalanche"
,"Rosetta Stone"
,"Rubella Ballet"
,"RRRRRRR"
,"VALUES(VALUES(VALUES(S)))"
,"Sad Lovers And Giants"
,"Salvation"
,"Santo Oficio"
,"Sator Codex"
,"Satori"
,"Scarecrow"
,"Scarlet And The Spooky Spiders"
,"Scarlet Leaves"
,"Scarlet s Remains"
,"Scary Bitches"
,"Screaming Banshee Aircrew"
,"Screaming Dead"
,"Screams For Tina"
,"Scream Silence"
,"S.C.U.M"
,"Secret Discovery"
,"Second Skin"
,"Sepulcrum Mentis"
,"Seraphin Twin"
,"SexAndBlood"
,"Sexbeat"
,"Sex Gang Children"
,"Sex Should Be Female"
,"Shadow Dance"
,"Shadowplay"
,"Shadow Project"
,"Shadow Of Fear"
,"Shallow Graves"
,"She Dies Alone"
,"She Wants Revenge"
,"Shroud"
,"Siiiii"
,"Siouxsie and The Banshees"
,"Sisters Of Mercy"
,"Sisters Of Murphy"
,"Skeletal Family"
,"Sky Fades Away"
,"Sky‚Äôs Gone Out"
,"Slaveshadow"
,"Sleeping Children"
,"Sleepmask"
,"Sociophobia"
,"Solemn Novena"
,"Sombrance"
,"Sons Of Neverland"
,"Sophya"
,"Sopor Aeternus And The Ensemble Of Shadows"
,"Soror Dolorosa"
,"Soulscape"
,"Southern Death Cult"
,"Spear Of Destiny"
,"Specimen"
,"Spiritual Bat"
,"Spiritual Bats"
,"Star Industry"
,"Stiff Kittens"
,"Stimmen Der Stille"
,"Stompcrash"
,"Stone 588"
,"Strange As Angels"
,"Strange Boutique"
,"Strange Dolls Cult"
,"Street Spirit"
,"Stun Gun"
,"Substance Of Dream"
,"Subterfuge"
,"Subtonix"
,"Sunset Down"
,"Sunshine Blind"
,"Super Heroines"
,"Suspiria"
,"Swandeath"
,"Swann Danger"
,"Swans Of Avon"
,"Taedium Vitae"
,"Tears For The Dying"
,"Tearwave"
,"Texas Vamps"
,"Thatch Noir"
,"Theatre Of Hate"
,"Theatre Of Ice"
,"They Feed At Night"
,"Thieves Of Silence"
,"Thirteen Bats"
,"This Burning Effigy"
,"This Window"
,"Thrill Of The Pull"
,"Tones on Tail"
,"Toy Attica"
,"Toys Went Berserk"
,"Tragic Black"
,"Trance To The Sun"
,"Trapodolls"
,"Triste Makrina"
,"Trouble Fait"
,"T.S.O.L."
,"Twisted Nerve"
,"Two Old Vamps"
,"Two Witches"
,"UK Decay"
,"UltraNoir"
,"Under A Purple Sky"
,"Under Two Flags"
,"Undying Legacy"
,"√öltima Dan√ßa"
,"Varjo"
,"VeilINSERT INTO bands VALUES( The"
,"Velvet Violet"
,"Vendemmian"
,"Vengeful Widows"
,"Vidi Aquam"
,"Violet Sky"
,"Violet Stigmata"
,"Virgin Prunes"
,"Voices Of Masada"
,"Voodoo Church"
,"Wailing Wall"
,"Wake"
,"Wartburgs F√ºr Walter"
,"Way Of All Flesh"
,"Whispers In The Shadow"
,"Witching Hour"
,"Wladislaw Draculesti"
,"Wounded"
,"Wreckage"
,"Your Favourite Nightmare"
,"XIII. Stolet√≠"
,"Xmal Deutschland"
,"Xymox"
,"Zadera"
,"Zeraphine"
,"Zero Le Creche"
,"Zombie Zex"
,"Zwarte Po√´zie"
,"Zombie Girl");

?>
<body>


<p>
 
</p>
<p>&nbsp;</p>
<p>&nbsp;</p>

<form action="<?php echo $editFormAction; ?>" method="post" name="form1" id="form1">
  <table align="center">
    <tr valign="baseline">
      <td nowrap="nowrap" align="right">Name:</td>
      <td><input type="text" name="name" value="" size="32" /></td>
    </tr>
    <tr valign="baseline">
      <td nowrap="nowrap" align="right">&nbsp;</td>
      <td><input type="submit" value="Insert record" /></td>
    </tr>
  </table>
  <input type="hidden" name="id" value="" />
  <input type="hidden" name="MM_insert" value="form1" />
</form>
<p>&nbsp;</p>

 <?php
  
  $temp = $arr;

 foreach ($bands as &$arr) {

   // echo"$arr";
   
 
	
	if($arr == $temp){
	
	    echo"$arr";
	}
	
	
	
	
 }


 
 
  ?>
</body>
</html>
<?php
mysql_free_result($Recordset1);
?>
